### ISSUE TITLE
(with Firefox Nightly) The 'Stylish' tab disappears on every Nightly re-launch (and you have to disable+re-enable the addon in order it to be displayed again)

### ISSUE THREAD

**Issue by darkred** [nt1m/stylish-devtool#10]
STR
(In Nightly 51 x64 (in win10 x64) with a fresh profile having either e10s on or off, it doesn't matter )
- install Stylish v2.0.7, restart Nightly, and then install SDT v1.0.7.  
  Observe in DevTools that the `Stylish` tab is displayed as expected.
- Now, close and re-launch Nightly: you'll notice that the `Stylish` tab is now missing.  
  You have to disable+re-enable the addon in order it to be displayed again - but, on next Nightly relaunch the issue will occur again.

PS. In FF48 the issue never occurs

**Comment by nt1m** [comment]
Thanks for reporting!
I've fixed this in version 1.0.8, which should arrive automatically by update once reviewed.
