### ISSUE TITLE
Can't get to work

### ISSUE THREAD

**Issue by mwoffenden** [nt1m/stylish-devtool#8]
I can't get the Stylish tab to show up in Firefox.  I do have Stylish installed.  Using 44.0b4 for Windows.

**Comment by nt1m** [comment]
Thanks for the report ! I'll fix it this weekend, feel free to ping me if I don't get to it by then

**Comment by mwoffenden** [comment]
Please add a note here when it's fixed and I'll test it out.

**Comment by nt1m** [comment]
@mwoffenden Fixed, can you test it out please ? Thanks !

**Comment by nt1m** [comment]
Here's a link to AMO: https://addons.mozilla.org/en-US/firefox/addon/stylish-developer-tool/versions/?page=1#version-1.0.2

**Comment by cubedj** [comment]
thanks - it works again ;))

**Comment by cubedj** [comment]
well - I judged too fast... the tab in devtools loads again but it won't load any styles (ReferenceError: StylishHelper is not defined / sidebar.js:17:9)... with Nightly 46.0a1 64bit...

**Comment by cubedj** [comment]
I missed this one > SyntaxError: redeclaration of const Cu / stylish-helper.js:1:13

**Comment by mwoffenden** [comment]
Same here.  I see the tab now but there are no styles listed.

**Comment by nt1m** [comment]
@mwoffenden @cubedj Ok, it should work now, v1.0.3 (tested myself): https://addons.mozilla.org/en-US/firefox/addon/stylish-developer-tool/versions/

**Comment by nt1m** [comment]
Thanks for the testing btw !

**Comment by cubedj** [comment]
ok - now it's really fixed ;)) good job :)

**Comment by mwoffenden** [comment]
Very nice, working now!
