### ISSUE TITLE
Broken on 45.0.2 ?

### ISSUE THREAD

**Issue by inspector71** [nt1m/stylish-devtool#9]
Doesn't seem to work in Firefox 45.0.2 with Stylish 2.0.6

**Comment by nt1m** [comment]
Sorry, I broke it for the release channel by fixing compat with nightly, I will fix that.

**Comment by inspector71** [comment]
Fair enough, these things happen :)

**Comment by nt1m** [comment]
@inspector71 Can you test if this version works for you ? Thanks!
[stylish-devtool-1.0.5.xpi.zip](https://github.com/nt1m/stylish-devtool/files/253514/stylish-devtool-1.0.5.xpi.zip)

**Comment by nt1m** [comment]
Nevermind, I have a version that works now (which I've tested).

**Comment by nt1m** [comment]
The latest version on AMO should now work with Firefox 46. Please re-open if not.
